### ISSUE TITLE
Adjust default sort order for articles index

### ISSUE THREAD

**Issue by paulrgn** [dadi/publish#394] opened 2018-06-12 08:53 UTC
### Expected behavior
Articles index (http://publish.dadi.cloud/articles) shows newest articles first by default

### Actual behavior
Shows oldest articles first

### Steps to reproduce the problem
Visit http://publish.dadi.cloud/articles

### Package details
n/a

**Comment by jimlambie** [comment] 2018-06-12 08:55
Related to https://github.com/dadi/publish/issues/372

**Comment by paulrgn** [comment] 2018-06-12 08:55
@abovedave is this a duplicate of https://github.com/dadi/publish/issues/372?

**Comment by paulrgn** [comment] 2018-06-12 08:56
@jimlambie great minds...

**Comment by eduardoboucas** [comment] 2018-06-12 08:56
Hey, is this a duplicate of #372?

(Sorry.)

**Closed** 2018-06-28 12:08 UTC
