### ISSUE TITLE
Navigating under an expired session results in 404 rather than redirect to login

### ISSUE THREAD

**Issue by danwdart** [dadi/publish#527] opened 2018-10-09 15:59 UTC
### Expected behavior
I've tried to access something I no longer have the cookies for, so I should be expected to log in.

### Actual behavior
Every route 404s,

### Steps to reproduce the problem
Remove cookies from current session or wait for their expiry, then click a menu item and observe it 404s.

### Package details
Latest publish

**Comment by eduardoboucas** [comment] 2018-10-11 16:36
What route are you seeing the 404 in? When I remove the cookie, routes actually work the same because the token is cached in the Redux store.

**Comment by eduardoboucas** [comment] 2018-11-22 15:55
This should have been fixed with #535. Could you please re-open if still an issue? Thanks!

**Comment by eduardoboucas** [comment] 2018-12-03 10:29
The issue is still there if the user's machine goes to sleep and then wakes up after the token has expired.

**Closed** 2018-12-03 11:33 UTC
Labels: product: Publish, type: bug
