### ISSUE TITLE
"Go to page" input

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#376] opened 2018-06-06 13:26 UTC
### Expected behavior

<img width="431" alt="screen shot 2018-06-06 at 14 25 59" src="https://user-images.githubusercontent.com/649231/41040877-8fbf4b22-6995-11e8-9ff5-33d95f46f225.png">

### Actual behavior

<img width="464" alt="screen shot 2018-06-06 at 14 25 31" src="https://user-images.githubusercontent.com/649231/41040886-94d22b7a-6995-11e8-9bd9-503e08a2204d.png">

**Comment by anaumovets** [comment] 2018-07-25 12:08
Looks like this has been fixed somewhere along the way.
@abovedave please confirm and I'll close it.

**Comment by jimlambie** [comment] 2018-07-26 10:05
@anaumovets this one still looks to be an issue. Exactly _what_ the issue is remains unclear though!

I think the input field needs to be narrower, with the cursor aligned to the left. The text "Showing 1-10 of 40" should then no longer wrap to a second line.

**Closed** 2018-07-30 14:06 UTC
